name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Git repository URL"
        required: true
        default: "https://github.com/android/sunflower"
      jdkVersion:
        description: "OpenJDK version to use: 8 / 11 / 17 etc."
        required: false
        default: "11"
      taskName:
        description: "build.gradle task name: assemble[Flavor]Debug"
        required: false
        default: "assembleDebug"

jobs:
  build:
    runs-on: ubuntu-latest # Android SDK is built-in in this image
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ github.event.inputs.jdkVersion }}

      - name: Clone project
        run: git clone --depth=1 ${{ github.event.inputs.repository }} workspace

      - name: Build APK
        working-directory: ./workspace
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew ${{ github.event.inputs.taskName }} --stacktrace

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: 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
        with:
          tag_name: v1.0.0 # Set the tag name for the release
          release_name: Release v1.0.0 # Set the name for the release
          draft: false
          prerelease: false

      - name: Upload the APK artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./**/*.apk
          name: apk-archive

      - name: Add APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: 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
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./**/*.apk
          asset_name: ${{ github.run_id }}.apk
          asset_content_type: application/vnd.android.package-archive

